Repository boostcampwm-2022/iOS09-burstcamp, pull requests merged in 2022-11, with the labels that each got.

#41 [Feature] coordinator 패턴 기초 구현
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/Auth/LoginViewController.swift
  Eoljuga/Eoljuga/Coordinator/AppCoordinator.swift
  Eoljuga/Eoljuga/Coordinator/AuthCoordinator.swift
  Eoljuga/Eoljuga/Coordinator/Coordinator.swift
  Eoljuga/Eoljuga/Coordinator/TabBarCoordinator.swift
  Eoljuga/Eoljuga/SceneDelegate.swift
  Eoljuga/Eoljuga/Tab/Bookmark/BookmarkViewController.swift
  Eoljuga/Eoljuga/Tab/Home/HomeViewController.swift
  Eoljuga/Eoljuga/Tab/MyPage/MyPageViewController.swift
Labels: feature, 빨리

#44 [Color] Custom Color Set 추가
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/black.colorset/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/blue.colorset/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/green.colorset/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/indigo.colorset/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/orange.colorset/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/pink.colorset/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/purple.colorset/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/red.colorset/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/teal.colorset/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/white.colorset/Contents.json
  Eoljuga/Eoljuga/Resource/Assets.xcassets/Colors/yellow.colorset/Contents.json
Labels: type: feature, 늘이

#47 Feature/home collectionview
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/Coordinator/AuthCoordinator.swift
  Eoljuga/Eoljuga/Coordinator/TabBarCoordinator.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/DefaultFeedCell.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/HomeViewController.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/UICollectionViewCell+identifier.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/UINavigationController+navigationBar.swift
  Eoljuga/Eoljuga/Util/Extension/UIColor+ColorSet.swift
  Eoljuga/Eoljuga/Util/Extension/UIFont+FontSet.swift
  Eoljuga/Eoljuga/Util/Protocol/ReusableView.swift
Labels: type: feature, 유탁

#50 Feature/home collectionview cell
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/Scene/Tab/Home/DefaultFeedCell.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/DefaultFeedCell/DefaultFeedCell.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/DefaultFeedCell/Footer/DefaultFeedCellFooter.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/DefaultFeedCell/Header/DefaultFeedCellBadgeStackView.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/DefaultFeedCell/Header/DefaultFeedCellHeader.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/DefaultFeedCell/Main/DefaultFeedCellMain.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/HomeViewController.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/UICollectionViewCell+identifier.swift
  Eoljuga/Eoljuga/Util/Extension/Constant.swift
  Eoljuga/Eoljuga/Util/Extension/TypeCasting.swift
  Eoljuga/Eoljuga/Util/Extension/UILabel+LineHeight.swift
  Eoljuga/Eoljuga/Util/Extension/UIStackView+addArrangedSubviews.swift
  Eoljuga/Eoljuga/Util/Extension/UIView+addSubViews.swift
Labels: type: feature, 유탁

#51 Feature/coordinator fix navigation 중복
  Eoljuga/Eoljuga/App/AppDelegate.swift
  Eoljuga/Eoljuga/App/SceneDelegate.swift
  Eoljuga/Eoljuga/Coordinator/AppCoordinator.swift
  Eoljuga/Eoljuga/Coordinator/AuthCoordinator.swift
  Eoljuga/Eoljuga/Coordinator/Coordinator.swift
  Eoljuga/Eoljuga/Coordinator/TabBarCoordinator.swift
  Eoljuga/Eoljuga/Coordinator/TabBarPage.swift
  Eoljuga/Eoljuga/Scene/Auth/LoginViewController.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/MyPageViewController.swift
Labels: type: enhancement, 승민

#52 LogIn View 추가
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/App/SceneDelegate.swift
  Eoljuga/Eoljuga/Coordinator/AuthCoordinator.swift
  Eoljuga/Eoljuga/Resource/Generated/Colors+Generated.swift
  Eoljuga/Eoljuga/Resource/Generated/Fonts+Generated.swift
  Eoljuga/Eoljuga/Scene/Auth/LogIn/GithubModel.swift
  Eoljuga/Eoljuga/Scene/Auth/LogIn/LogInView.swift
  Eoljuga/Eoljuga/Scene/Auth/LogIn/LogInViewModel.swift
  Eoljuga/Eoljuga/Scene/Auth/LogIn/LoginViewController.swift
  Eoljuga/Eoljuga/Scene/Auth/LogInManager.swift
  Eoljuga/Eoljuga/Scene/Auth/LoginViewController.swift
Labels: type: feature, 기훈

#60 xcodeproj crash 해결
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Eoljuga/Eoljuga/Coordinator/AppCoordinator.swift
  Eoljuga/Eoljuga/Coordinator/AuthCoordinator.swift
  Eoljuga/Eoljuga/Coordinator/Base/Coordinator.swift
  Eoljuga/Eoljuga/Coordinator/Coordinator.swift
  Eoljuga/Eoljuga/Coordinator/CoordinatorEvent.swift
  Eoljuga/Eoljuga/Coordinator/CoordinatorPublisher.swift
  Eoljuga/Eoljuga/Model/.gitkeep
  Eoljuga/Eoljuga/Scene/Auth/LogIn/APIKey.swift
  Eoljuga/Eoljuga/Scene/Auth/LogIn/LoginViewController.swift
  Eoljuga/Eoljuga/Scene/Common/View/.gitkeep
  Eoljuga/Eoljuga/Scene/Common/ViewModel/.gitkeep
  Eoljuga/Eoljuga/Service/LogInManager.swift
  Eoljuga/Eoljuga/Util/Constant/Constant.swift
  Eoljuga/Eoljuga/Util/Extension/TypeConversion.swift
  Eoljuga/Eoljuga/Util/Extension/UICollectionViewCell+identifier.swift
  Eoljuga/EoljugaTests/EoljugaTests.swift
  Eoljuga/EoljugaUITests/EoljugaUITests.swift
  Eoljuga/EoljugaUITests/EoljugaUITestsLaunchTests.swift
Labels: type: bug, priority: 긴급

#61 [마이페이지] 상단 프로필뷰 구현 (버그주의)
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/Coordinator/TabBarCoordinator.swift
  Eoljuga/Eoljuga/Model/Domain.swift
  Eoljuga/Eoljuga/Model/User.swift
  Eoljuga/Eoljuga/Scene/Common/View/DefaultBadgeLabel.swift
  Eoljuga/Eoljuga/Scene/Common/View/DefaultBadgeView.swift
  Eoljuga/Eoljuga/Scene/Common/View/DefaultButton.swift
  Eoljuga/Eoljuga/Scene/Common/View/DefaultProfileImageView.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/MyPageViewController.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/View/MyPageProfileView.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/View/MyPageView.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift
  Eoljuga/Eoljuga/Util/Constant/Constant.swift
Labels: type: bug, type: feature, 늘이

#64 Feature/domain
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/App/SceneDelegate.swift
  Eoljuga/Eoljuga/Coordinator/AuthCoordinator.swift
  Eoljuga/Eoljuga/Model/APIKey.swift
  Eoljuga/Eoljuga/Model/Domain.swift
  Eoljuga/Eoljuga/Scene/Auth/LogIn/LogInView.swift
  Eoljuga/Eoljuga/Scene/Auth/LogIn/LoginViewController.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/CamperID/SignUpCamperIDView.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/Domain/SighUpDomainView.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/Domain/SignUpDomainViewController.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/SignUpViewModel.swift
  Eoljuga/Eoljuga/Service/LogInManager.swift
Labels: type: feature, 기훈

#65 [홈] 추천 피드 - CompostionalLayout 사용해서 구현
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/Scene/Tab/Home/FeedCellType.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/HomeView.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/HomeViewController.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/NormalFeedCell/Footer/NormalFeedCellFooter.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/NormalFeedCell/Header/NormalFeedCellBadgeStackView.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/NormalFeedCell/Header/NormalFeedCellHeader.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/NormalFeedCell/Main/NormalFeedCellMain.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/NormalFeedCell/NormalFeedCell.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/RecommendFeedSection/RecommendFeedCell.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/RecommendFeedSection/RecommendFeedHeader.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/RecommendFeedSection/RecommendFeedUserView.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/UINavigationController+navigationBar.swift
  Eoljuga/Eoljuga/Util/Constant/Constant.swift
  Eoljuga/Eoljuga/Util/Extension/UI+ReusableView.swift
  Eoljuga/Eoljuga/Util/Extension/UICollectionViewCell+identifier.swift
Labels: type: feature, 유탁

#66 [마이페이지 설정] CollectionView List 사용 #56
  Eoljuga/Eoljuga/Scene/Common/View/DefaultBadgeLabel.swift
  Eoljuga/Eoljuga/Scene/Common/View/DefaultProfileImageView.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/View/MyPageView.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  Eoljuga/Eoljuga/Util/Constant/Constant.swift
Labels: type: feature, 늘이

#67 [네트워크, FireStore] URLSession + FireStore rest
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/Model/UserDTO.swift
  Eoljuga/Eoljuga/Service/FireStoreService.swift
  Eoljuga/Eoljuga/Service/URLSessionService.swift
  Eoljuga/Eoljuga/Util/Constant/FireStoreConfiguration.swift
  Eoljuga/Eoljuga/Util/Constant/HTTPMethod.swift
  Eoljuga/Eoljuga/Util/Constant/NetworkError.swift
  Eoljuga/Eoljuga/Util/Query/FireStoreValues.swift
  Eoljuga/Eoljuga/Util/Query/Query.swift
  Eoljuga/Eoljuga/Util/Query/UserQuery.swift
Labels: type: feature, priority: 빨리, 늘이

#70 FireStoreValues 분리
  Eoljuga/.swiftlint.yml
Labels: type: feature, 늘이

#71 Feature/home navigation
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/App/SceneDelegate.swift
  Eoljuga/Eoljuga/Coordinator/TabBarCoordinator.swift
  Eoljuga/Eoljuga/Scene/Tab/Bookmark/BookmarkViewController.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/View/FeedCellType.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/View/HomeView.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/View/NormalFeedCell/Footer/NormalFeedCellFooter.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/View/NormalFeedCell/Header/NormalFeedCellBadgeStackView.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/View/NormalFeedCell/Header/NormalFeedCellHeader.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/View/NormalFeedCell/Main/NormalFeedCellMain.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/View/NormalFeedCell/NormalFeedCell.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedHeader.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedUserView.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/ViewController/HomeViewController.swift
  Eoljuga/Eoljuga/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  Eoljuga/Eoljuga/Scene/Tab/ScrapPage/View/ScrapPageView.swift
  Eoljuga/Eoljuga/Scene/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  Eoljuga/Eoljuga/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  Eoljuga/Eoljuga/Util/Extension/UINavigationController+configure.swift
Labels: type: feature, 유탁

#73 [마이페이지] 오픈소스 라이선스 View 구현
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/Scene/Tab/MyPage/View/OpenSourceLicenseView.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/ViewController/OpenSourceLicenseViewController.swift
Labels: type: feature, 늘이

#77 [마이페이지] 코드리뷰 반영
  Eoljuga/Eoljuga/Scene/Tab/MyPage/View/OpenSourceLicenseView.swift
Labels: 늘이

#78 Feature/signupdomain
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/Coordinator/AuthCoordinator.swift
  Eoljuga/Eoljuga/Scene/Auth/LogIn/LogInView.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/CamperID/SignUpCamperIDView.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/Domain/SighUpDomainView.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/SignUpViewModel.swift
  Eoljuga/Eoljuga/Scene/Common/View/DefaultButton.swift
  Eoljuga/Eoljuga/Util/Constant/Constant.swift
Labels: type: feature, 기훈

#81 feat: blog 입력 화면 만들기
  Eoljuga/Eoljuga/Coordinator/AuthCoordinator.swift
  Eoljuga/Eoljuga/Scene/Auth/LogIn/LogInView.swift
  Eoljuga/Eoljuga/Scene/Auth/LogIn/LoginViewController.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/CamperID/SignUpCamperIDView.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/Domain/SighUpDomainView.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/Domain/SignUpDomainViewController.swift
  Eoljuga/Eoljuga/Scene/Auth/SignUp/SignUpViewModel.swift
  Eoljuga/Eoljuga/Util/Constant/Constant.swift
Labels: type: feature, 기훈

#82 Firebase-Functions에서 RSS Crawling 구현
  Firebase-Functions/.firebaserc
  Firebase-Functions/.gitignore
  Firebase-Functions/firebase.json
  Firebase-Functions/functions/.eslintrc.js
  Firebase-Functions/functions/.gitignore
  Firebase-Functions/functions/index.js
  Firebase-Functions/functions/package-lock.json
  Firebase-Functions/functions/package.json
  Firebase-Functions/functions/service/feedAPI.js
  Firebase-Functions/functions/service/firestoreManager.js
  Firebase-Functions/functions/util.js
Labels: type: feature, 승민

#91 [마이페이지] 수정 view
  Eoljuga/Eoljuga.xcodeproj/project.pbxproj
  Eoljuga/Eoljuga/Model/CellIndexPath.swift
  Eoljuga/Eoljuga/Scene/Common/View/DefaultBadgeLabel.swift
  Eoljuga/Eoljuga/Scene/Common/View/DefaultImageLabel.swift
  Eoljuga/Eoljuga/Scene/Common/View/DefaultProfileImageView.swift
  Eoljuga/Eoljuga/Scene/Common/View/DefaultTextField.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/View/MyPageEditView.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/View/MyPageProfileView.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/View/OpenSourceLicenseView.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/View/SettingCell.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/View/SettingSection.swift
  Eoljuga/Eoljuga/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  Eoljuga/Eoljuga/Util/Constant/Constant.swift
  Eoljuga/Eoljuga/Util/Extension/UIStackView+addArrangedSubviews.swift
Labels: type: feature, 늘이

#94 [홈] 컬러 수정
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Coordinator/TabBarCoordinator.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Footer/NormalFeedCellFooter.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Header/NormalFeedCellBadgeStackView.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Header/NormalFeedCellHeader.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/HomeView.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedHeader.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/View/ScrapPageView.swift
Labels: type: enhancement, 유탁

#99 Feed detail UI 구현
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Scene/Common/View/DefaultMultilLineLabel.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultUserInfoView.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Scene/Tab/Detail/View/FeedDetailView.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewController/FeedDetailViewController.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedHeader.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
Labels: type: feature, 승민

#100 Feature/githublogin
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/Info.plist
  burstcamp/burstcamp/App/SceneDelegate.swift
  burstcamp/burstcamp/Coordinator/AppCoordinator.swift
  burstcamp/burstcamp/Model/APIKey.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInViewModel.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDView.swift
  burstcamp/burstcamp/Service/FireStoreService.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Service/URLSessionService.swift
  burstcamp/burstcamp/Util/Constant/NetworkError.swift
Labels: type: feature, 기훈

#101 [기능] 시간 포매팅
  burstcamp/.swiftlint.yml
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp.xcodeproj/xcshareddata/xcschemes/burstcamp.xcscheme
  burstcamp/burstcamp/Util/BCDateFormatter.swift
  burstcamp/burstcamp/Util/Extension/Date+.swift
  burstcamp/burstcamp/Util/Extension/TimeInterval+.swift
  burstcamp/burstcampTests/burstcampTests.swift
Labels: type: feature, type: test, 유탁

#103 [마이페이지] ViewModel
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp/Coordinator/TabBarCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBarCoordinatorEvent.swift
  burstcamp/burstcamp/Model/Blog.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultImageLabel.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageEditView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageEditViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift
  burstcamp/burstcamp/Util/Constant/Constant.swift
  burstcamp/burstcamp/Util/Constant/MyPageEditValidationResult.swift
  burstcamp/burstcamp/Util/Extension/UIViewController+ToastMessage.swift
  burstcamp/burstcamp/Util/Validation/BlogLinkValidation.swift
  burstcamp/burstcamp/Util/Validation/NickNameValidation.swift
Labels: type: feature, 늘이

#105 [기능] refresh Control
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp/Scene/Tab/Home/View/HomeView.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/View/ScrapPageView.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Util/Extension/CombineUIkit/UIControl+Combine.swift
  burstcamp/burstcamp/Util/Extension/Type/Date+FormatString.swift
  burstcamp/burstcamp/Util/Extension/Type/TimeInterval+.swift
  burstcamp/burstcamp/Util/Extension/Type/TypeConversion.swift
  burstcamp/burstcamp/Util/Extension/UI/UI+ReusableView.swift
  burstcamp/burstcamp/Util/Extension/UI/UIColor+ColorSet.swift
  burstcamp/burstcamp/Util/Extension/UI/UIFont+FontSet.swift
  burstcamp/burstcamp/Util/Extension/UI/UILabel+LineHeight.swift
  burstcamp/burstcamp/Util/Extension/UI/UINavigationController+configure.swift
  burstcamp/burstcamp/Util/Extension/UI/UIStackView+addArrangedSubviews.swift
  burstcamp/burstcamp/Util/Extension/UI/UIView+addSubViews.swift
  burstcamp/burstcamp/Util/Protocol/ContainCollectionView.swift
Labels: type: feature, 유탁

#108 [공통] 네비게이션, 탭바 배경색 iOS 15 이상 대응
  burstcamp/burstcamp/Coordinator/AppCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBarCoordinator.swift
  burstcamp/burstcamp/Util/Extension/UIViewController+ToastMessage.swift
Labels: type: bug, 늘이

#109 [Firebase] URLSessionService 리팩토링
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Model/Blog.swift
  burstcamp/burstcamp/Model/BlogDTO.swift
  burstcamp/burstcamp/Model/FireStoreResult.swift
  burstcamp/burstcamp/Model/User.swift
  burstcamp/burstcamp/Model/UserDTO.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageEditView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift
  burstcamp/burstcamp/Service/FireStoreService.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Service/URLSessionService.swift
  burstcamp/burstcamp/Util/Constant/FireStoreConfiguration.swift
  burstcamp/burstcamp/Util/Constant/HTTPHeader.swift
  burstcamp/burstcamp/Util/Constant/NetworkError.swift
  burstcamp/burstcamp/Util/Query/BlogQuery.swift
  burstcamp/burstcamp/Util/Query/UserQuery.swift
Labels: type: feature, 늘이

#111 fix: Lint 오류 수정
  burstcamp/burstcamp/Service/FireStoreService.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Util/Constant/HTTPHeader.swift
  burstcamp/burstcamp/Util/Query/BlogQuery.swift
Labels: type: bug, priority: 긴급

#110 [홈] 목업 데이터로 업데이트
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp/Model/Feed.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultBadgeLabel.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultBadgeView.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultUserInfoView.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Footer/NormalFeedCellFooter.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
Labels: type: feature, 유탁

#112 [Asset] 앱 아이콘 추가
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  burstcamp/burstcamp/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: type: feature, priority: 빨리, 유탁

#114 feat: loginflow에 combine 적용
  burstcamp/burstcamp/Coordinator/AuthCoordinator.swift
  burstcamp/burstcamp/Coordinator/AuthCoordinatorEvent.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
  burstcamp/burstcamp/Service/LogInManager.swift
Labels: type: feature, 기훈

#117 Feed detail - WebView 돌려깎기
  Firebase-Functions/functions/package-lock.json
  Firebase-Functions/functions/package.json
  Firebase-Functions/functions/service/feedAPI.js
  Firebase-Functions/functions/service/firestoreManager.js
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp/Scene/Tab/Detail/View/FeedContentWebView.swift
  burstcamp/burstcamp/Scene/Tab/Detail/View/FeedDetailView.swift
  burstcamp/burstcamp/Scene/Tab/Detail/View/MockHTMLString.swift
Labels: type: enhancement, 승민

#120 [캐시] 이미지 캐시 구현
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Service/ImageCacheManager.swift
  burstcamp/burstcamp/Service/UserDefaultsManager.swift
  burstcamp/burstcamp/Util/Constant/ImageCacheError.swift
  burstcamp/burstcamp/Util/Extension/UI/UIImageView+Cache.swift
  burstcamp/burstcamp/Util/Extension/UI/UIViewController+ToastMessage.swift
Labels: type: feature, 늘이

#118 feat: 자동로그인 구현, 멤버 여부에 따른 로직, 가입 되어있는지에 따른 로직 추가
  burstcamp/burstcamp/Coordinator/AuthCoordinator.swift
  burstcamp/burstcamp/Coordinator/AuthCoordinatorEvent.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/SignUpViewModel.swift
  burstcamp/burstcamp/Service/LogInManager.swift
Labels: type: feature, 기훈

#123 [Color] feed colorset 추가
  burstcamp/burstcamp/Resource/Colors.xcassets/brightGreen.colorset/Contents.json
  burstcamp/burstcamp/Resource/Colors.xcassets/brightOrange.colorset/Contents.json
  burstcamp/burstcamp/Resource/Colors.xcassets/brightYellow.colorset/Contents.json
  burstcamp/burstcamp/Resource/Generated/Colors+Generated.swift
  burstcamp/burstcamp/Util/Extension/UI/UIColor+ColorSet.swift
Labels: type: feature, 늘이

#121 feat: camperID 3자리 맞추기
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp/Coordinator/AuthCoordinator.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/SignUpViewModel.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultTextField.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Util/Constant/NetworkError.swift
  burstcamp/burstcamp/Util/Extension/CombineUIkit/UIControl+Combine.swift
Labels: type: feature, 기훈

#124 [푸시알림] 권한, foreground, background 탭할시 Coordinator 작업
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/App/Info.plist
  burstcamp/burstcamp/Coordinator/AppCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBarCoordinator.swift
  burstcamp/burstcamp/Model/FCMToken.swift
  burstcamp/burstcamp/Service/FirestoreFCMToken.swift
  burstcamp/burstcamp/Util/Extension/Type/Encodable+dictionary.swift
  burstcamp/burstcamp/Util/Extension/Type/Notification+.swift
  burstcamp/burstcamp/burstcamp.entitlements
Labels: type: feature, 늘이

#125 fetchBlogTitle API 만들었어요
  Firebase-Functions/functions/index.js
  Firebase-Functions/functions/service/feedAPI.js
  Firebase-Functions/functions/util.js
Labels: type: feature, type: suggestion, 승민

#128 [리팩토링] Firestore 모델 수정
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Model/Blog.swift
  burstcamp/burstcamp/Model/BlogDTO.swift
  burstcamp/burstcamp/Model/Feed.swift
  burstcamp/burstcamp/Model/FireStoreResult.swift
  burstcamp/burstcamp/Model/ScrapUser.swift
  burstcamp/burstcamp/Model/User.swift
  burstcamp/burstcamp/Model/UserDTO.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultBadgeView.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultUserInfoView.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageEditView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageEditViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift
  burstcamp/burstcamp/Service/FireStoreService.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Util/Constant/FireStoreConfiguration.swift
  burstcamp/burstcamp/Util/Query/BlogQuery.swift
  burstcamp/burstcamp/Util/Query/FireStoreValues.swift
  burstcamp/burstcamp/Util/Query/Query.swift
  burstcamp/burstcamp/Util/Query/UserQuery.swift
Labels: priority: 빨리, type: suggestion

#126 [validation] 이름, 캠퍼아이디, 블로그 주소 유효성 검사 및 테스트
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Service/FireFunctionsManager.swift
  burstcamp/burstcamp/Util/Constant/URLRegularExpression.swift
  burstcamp/burstcamp/Util/Validation/BlogLinkValidation.swift
  burstcamp/burstcamp/Util/Validation/NickNameValidation.swift
  burstcamp/burstcamp/Util/Validation/Validation.swift
  burstcamp/burstcampTests/ValidationTest.swift
Labels: type: feature, type: test, 기훈, 늘이

#129 [홈] 파이어베이스에서 피드 가져오기
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Coordinator/TabBarCoordinator.swift
  burstcamp/burstcamp/Model/Feed.swift
  burstcamp/burstcamp/Model/Feed/Feed.swift
  burstcamp/burstcamp/Model/Feed/FeedDTO.swift
  burstcamp/burstcamp/Model/Feed/FeedWriter.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultBadgeView.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultUserInfoView.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/HomeView.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeFireStore.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Util/Error/FirebaseError.swift
  burstcamp/burstcamp/Util/Error/ImageCacheError.swift
  burstcamp/burstcamp/Util/Error/NetworkError.swift
Labels: type: feature, 유탁

#130 [파이어베이스] 임시 user Firebase
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Model/User.swift
  burstcamp/burstcamp/Service/FirestoreUser.swift
  burstcamp/burstcamp/Service/UserManager.swift
  burstcamp/burstcamp/Util/Constant/FirestoreError.swift
Labels: type: feature, 늘이

#131 hotfix: project file
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Model/User.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift
  burstcamp/burstcamp/Service/FirestoreUser.swift
  burstcamp/burstcamp/Service/UserManager.swift
  burstcamp/burstcamp/Util/Validation/Validation.swift
Labels: priority: 긴급
