Repository boostcampwm-2022/iOS09-burstcamp, pull requests merged in 2022-12, with the labels that each got.

#133 FeedDetail View 기능 구현 - 스크랩기능 빼고
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Model/Feed/FeedWriter.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultToggleButton.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultUserInfoView.swift
  burstcamp/burstcamp/Scene/Tab/Detail/View/FeedDetailView.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewController/FeedDetailViewController.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
Labels: type: feature, 승민

#137 [홈] taskGroup을 사용해 추천피드 받아오기
  burstcamp/burstcamp/Model/Domain.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedUserView.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
Labels: type: feature, priority: 빨리, 유탁

#141 Feed detail 스크랩 버튼 로직 구현
  burstcamp/burstcamp/Scene/Common/View/DefaultToggleButton.swift
  burstcamp/burstcamp/Scene/Tab/Detail/View/FeedDetailView.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewController/FeedDetailViewController.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewModel/FeedDetailViewModel.swift
Labels: type: feature, 승민

#138 [공통] 블로그 주소 검증 & alert
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Coordinator/AuthCoordinator.swift
  burstcamp/burstcamp/Coordinator/AuthCoordinatorEvent.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInViewModel.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewModel.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewModel.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/SignUpViewModel.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Service/UserManager.swift
  burstcamp/burstcamp/Util/Extension/UI/UIViewController+.swift
Labels: type: feature, 기훈

#140 [홈] 페이지네이션 & taskGroup 사용
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp/Coordinator/TabBarCoordinator.swift
  burstcamp/burstcamp/Model/Domain.swift
  burstcamp/burstcamp/Model/Feed/FeedWriter.swift
  burstcamp/burstcamp/Model/User.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultUserInfoView.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/HomeView.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedUserView.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeFireStore.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Util/Constant/FireStoreConfiguration.swift
  burstcamp/burstcamp/Util/Error/FirebaseError.swift
  burstcamp/burstcamp/Util/Extension/UI/UIScrollView+.swift
Labels: type: feature, 유탁

#145 데이터베이스끼리의 연동을 위한 데이터수집 로직 개선
  Firebase-Functions/functions/model.js
  Firebase-Functions/functions/package-lock.json
  Firebase-Functions/functions/package.json
  Firebase-Functions/functions/service/feedAPI.js
  Firebase-Functions/functions/service/firestoreManager.js
  Firebase-Functions/functions/util.js
  burstcamp/burstcamp/Model/Feed/Feed.swift
  burstcamp/burstcamp/Model/Feed/FeedDTO.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
  burstcamp/burstcamp/Scene/Tab/Detail/View/FeedDetailView.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
Labels: type: feature, 승민

#147 [마이페이지, 유저처리] 리팩토링 및 기능
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/SceneDelegate.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultImageLabel.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultProfileImageView.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultTextField.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageEditView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageProfileView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageEditViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift
  burstcamp/burstcamp/Service/FireFunctionsManager.swift
  burstcamp/burstcamp/Service/FireStorageService.swift
  burstcamp/burstcamp/Service/FirestoreUser.swift
  burstcamp/burstcamp/Service/UserManager.swift
  burstcamp/burstcamp/Util/Constant/Alert.swift
  burstcamp/burstcamp/Util/Constant/MyPageEditValidationResult.swift
  burstcamp/burstcamp/Util/Error/FireStorageError.swift
  burstcamp/burstcamp/Util/Extension/UI/UIViewController+.swift
Labels: type: feature, 늘이

#151 [에러처리] 깃헙 로그인 시 앱이 죽어버리던 오류 해결
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Model/Domain.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewModel.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewModel.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Util/Extension/UI/UIViewController+.swift
Labels: type: bug, 기훈

#152 [Hotfix] Feed 모델 프로퍼티 바뀐거 수정
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift
Labels: type: bug, priority: 긴급, 유탁

#155 [테스트] coordinator함수 호출 부 print문 추가
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Service/LogInManager.swift
Labels: type: test, 기훈

#157 [로고] AppIcon 버캠러 다이어트
  burstcamp/burstcamp/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon.png
Labels: type: enhancement, 늘이

#158 [마이페이지] 리팩토링
  burstcamp/burstcamp/Model/Domain.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultImageLabel.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultTextField.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageEditView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift
  burstcamp/burstcamp/Util/Constant/MyPageEditValidationResult.swift
  burstcamp/burstcamp/Util/Extension/UI/UIViewController+.swift
  burstcamp/burstcamp/Util/Validation/Validation.swift
Labels: type: enhancement, 늘이

#156 [유저 정보처리] 키체인 추가
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Coordinator/AppCoordinator.swift
  burstcamp/burstcamp/Service/FireStorageService.swift
  burstcamp/burstcamp/Service/KeyChainManager.swift
  burstcamp/burstcamp/Service/UserManager.swift
Labels: type: feature, 늘이

#163 [오류수정] hotfix
  burstcamp/burstcamp/Model/Domain.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageEditViewModel.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
Labels: type: bug, priority: 긴급, 늘이

#161 feat: build action
  .github/workflows/build.yml
  .github/workflows/build_test.yml
  .github/workflows/swiftlint.yml
Labels: type: enhancement, 승민

#160 [refactor] Date -> timeStamp 변경
  burstcamp/burstcamp/Model/User.swift
  burstcamp/burstcamp/Service/FirestoreUser.swift
Labels: 기훈

#165 [피드 셀] 스크랩 버튼 클릭시 서버(파이어베이스)에 업데이트
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Model/Feed/Feed.swift
  burstcamp/burstcamp/Model/Feed/FeedDTO.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultToggleButton.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Footer/NormalFeedCellFooter.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Scene/Common/ViewModel/NormalFeedCellViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  burstcamp/burstcamp/Service/ImageCacheManager.swift
  burstcamp/burstcamp/Util/Constant/FireStoreConfiguration.swift
Labels: type: feature, 유탁

#174 [UI] 버캠러 100*100 아이콘 추가
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Coordinator/AppCoordinator.swift
  burstcamp/burstcamp/Resource/Assets.xcassets/burstcamper100.imageset/Contents.json
  burstcamp/burstcamp/Resource/Assets.xcassets/burstcamper100.imageset/burstcamper100.png
  burstcamp/burstcamp/Resource/Assets.xcassets/burstcamper100.imageset/burstcamper100@2x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/burstcamper100.imageset/burstcamper100@3x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/burstcamper100.imageset/burstcamper100_Dark.png
  burstcamp/burstcamp/Resource/Assets.xcassets/burstcamper100.imageset/burstcamper100_Dark@2x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/burstcamper100.imageset/burstcamper100_Dark@3x.png
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SighUpDomainView.swift
  burstcamp/burstcamp/Util/Extension/UI/UIImage+Icon.swift
Labels: type: feature, 늘이

#175 [로그인] logIn error handling
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Coordinator/AppCoordinator.swift
  burstcamp/burstcamp/Coordinator/AuthCoordinator.swift
  burstcamp/burstcamp/Coordinator/AuthCoordinatorEvent.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInViewModel.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Util/Error/FirebaseError.swift
  burstcamp/burstcamp/Util/Error/GithubError.swift
  burstcamp/burstcamp/Util/Extension/UI/UIViewController+.swift
Labels: type: bug, 기훈

#180 [로그인 & 회원가입] View 리팩토링 - autolayout 수정
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Contents.json
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github.png
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github@2x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github@3x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github_dark.png
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github_dark@2x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github_dark@3x.png
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SighUpDomainView.swift
  burstcamp/burstcamp/Util/Constant/Constant.swift
  burstcamp/burstcamp/Util/Extension/UI/UIImage+Icon.swift
Labels: type: enhancement, 기훈

#179 [스크랩] 스크랩 클릭시 로컬에서 Up & Down 처리
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Scene/Common/ViewModel/FeedScrapViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/FeedCellType.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
Labels: type: feature, 유탁

#182 [Refactor] WKWebView Scroll -> ScrollView 안에 WKWebView 로 변경
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Scene/Tab/Detail/View/FeedContentWebView.swift
  burstcamp/burstcamp/Scene/Tab/Detail/View/FeedDetailView.swift
  burstcamp/burstcamp/Scene/Tab/Detail/View/FeedInfoStackView.swift
Labels: type: enhancement, 유탁

#194 [회원가입] throttle, blogTitle 확인 Alert 추가
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInViewModel.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
Labels: type: feature, 기훈

#196 [리팩토링] TabBarCoordinator 분리
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Coordinator/App/AppCoordinator.swift
  burstcamp/burstcamp/Coordinator/AppCoordinatorEvent.swift
  burstcamp/burstcamp/Coordinator/Auth/AuthCoordinator.swift
  burstcamp/burstcamp/Coordinator/AuthCoordinatorEvent.swift
  burstcamp/burstcamp/Coordinator/Base/ContainFeedDetailCoordinator.swift
  burstcamp/burstcamp/Coordinator/Base/Coordinator.swift
  burstcamp/burstcamp/Coordinator/Base/CoordinatorEvent.swift
  burstcamp/burstcamp/Coordinator/Home/HomeCoordinator.swift
  burstcamp/burstcamp/Coordinator/MyPage/MyPageCoordinator.swift
  burstcamp/burstcamp/Coordinator/ScrapPage/ScrapPageCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBar/TabBarPage.swift
  burstcamp/burstcamp/Coordinator/TabBarCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBarCoordinatorEvent.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewController/FeedDetailViewController.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageEditViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Util/Factory/Factory.swift
Labels: type: enhancement, 유탁

#197 feat: indicator 추가
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInViewModel.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
Labels: type: feature, 기훈

#190 [이미지 캐시] 정책 개선 및 사이즈 개선
  burstcamp/burstcamp/Service/ImageCacheManager.swift
  burstcamp/burstcamp/Util/Constant/Constant.swift
  burstcamp/burstcamp/Util/Extension/UI/UIImageView+Cache.swift
Labels: type: enhancement, 늘이

#198 Feature/module resource
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Resource/Generated/Colors+Generated.swift
  burstcamp/burstcamp/Util/Extension/UI/UIColor+ColorSet.swift
  burstcamp/burstcamp/Util/Extension/UI/UIFont+FontSet.swift
  burstcamp/burstcamp/Util/Extension/UI/UIImage+Icon.swift
  burstcamp/swiftgen.yml
  modules/BCResource/BCResource.xcodeproj/project.pbxproj
  modules/BCResource/BCResource.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  modules/BCResource/BCResource.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  modules/BCResource/BCResource/BCResource.h
  modules/BCResource/BCResource/ColorSet.swift
  modules/BCResource/BCResource/FontSet.swift
  modules/BCResource/BCResource/Generated/Assets+Generated.swift
  modules/BCResource/BCResource/Generated/Fonts+Generated.swift
  modules/BCResource/BCResource/ImageSet.swift
  modules/BCResource/BCResource/README.md
  modules/BCResource/BCResource/README_resource/Asset_Generated.png
  modules/BCResource/BCResource/README_resource/Structure.png
  modules/BCResource/BCResource/Resource/Color.xcassets/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/background.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/black.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/blue.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/brightGreen.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/brightOrange.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/brightYellow.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/brown.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/green.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/indigo.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/main.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/orange.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/pink.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/purple.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/red.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/teal.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/white.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Color.xcassets/yellow.colorset/Contents.json
  modules/BCResource/BCResource/Resource/Fonts/NanumSquareB.otf
  modules/BCResource/BCResource/Resource/Fonts/NanumSquareEB.otf
  modules/BCResource/BCResource/Resource/Fonts/NanumSquareR.otf
  modules/BCResource/BCResource/Resource/Image.xcassets/AppIcon.appiconset/AppIcon.png
  modules/BCResource/BCResource/Resource/Image.xcassets/AppIcon.appiconset/Contents.json
  modules/BCResource/BCResource/Resource/Image.xcassets/Contents.json
  modules/BCResource/BCResource/Resource/Image.xcassets/Github.imageset/Contents.json
  modules/BCResource/BCResource/Resource/Image.xcassets/Github.imageset/Github.png
  modules/BCResource/BCResource/Resource/Image.xcassets/Github.imageset/Github@2x.png
  modules/BCResource/BCResource/Resource/Image.xcassets/Github.imageset/Github@3x.png
  modules/BCResource/BCResource/Resource/Image.xcassets/Github.imageset/Github_dark.png
  modules/BCResource/BCResource/Resource/Image.xcassets/Github.imageset/Github_dark@2x.png
  modules/BCResource/BCResource/Resource/Image.xcassets/Github.imageset/Github_dark@3x.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamper100.imageset/Contents.json
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamper100.imageset/burstcamper100.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamper100.imageset/burstcamper100@2x.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamper100.imageset/burstcamper100@3x.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamper100.imageset/burstcamper100_Dark.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamper100.imageset/burstcamper100_Dark@2x.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamper100.imageset/burstcamper100_Dark@3x.png
  modules/BCResource/swiftgen.yml
Labels: type: enhancement, 승민

#201 [hotfix] Module폴더가 사라지는것 해결
  burstcamp/Modules/.gitkeep
Labels: type: bug, 승민

#203 [Firestore] ViewModel에서 Firestore 관련 함수 분리
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Coordinator/Base/ContainFeedDetailCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBarCoordinator.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Scene/Common/ViewModel/FeedScrapViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  burstcamp/burstcamp/Service/Firebase/FireFunctionsManager.swift
  burstcamp/burstcamp/Service/Firebase/FireStorageService.swift
  burstcamp/burstcamp/Service/Firebase/FirestoreCollection.swift
  burstcamp/burstcamp/Service/Firebase/FirestoreFeedService.swift
  burstcamp/burstcamp/Service/Firebase/FirestoreUser.swift
  burstcamp/burstcamp/Service/ImageCacheManager.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Util/Error/ConvertError.swift
  burstcamp/burstcamp/Util/Error/FireStorageError.swift
  burstcamp/burstcamp/Util/Error/FirebaseError.swift
  burstcamp/burstcamp/Util/Error/FirestoreError.swift
  burstcamp/burstcamp/Util/Error/GithubError.swift
  burstcamp/burstcamp/Util/Error/ImageCacheError.swift
  burstcamp/burstcamp/Util/Error/NetworkError.swift
Labels: type: enhancement, 유탁

#204 [탈퇴, 알림] 마이페이지 탈퇴 LoginManager 연동, 알림 functions 추가 및 코드작업
  Firebase-Functions/functions/index.js
  Firebase-Functions/functions/package-lock.json
  Firebase-Functions/functions/package.json
  Firebase-Functions/functions/service/apnsManager.js
  Firebase-Functions/functions/service/firestoreManager.js
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Coordinator/App/AppCoordinator.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/SettingCell.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift
  burstcamp/burstcamp/Service/FirestoreFCMToken.swift
  burstcamp/burstcamp/Service/UserDefaultsManager.swift
  burstcamp/burstcamp/Service/UserManager.swift
Labels: type: feature, 늘이

#209 [탈퇴] 유저 정보 삭제 함수 생성
  Firebase-Functions/functions/index.js
  Firebase-Functions/functions/service/firestoreManager.js
  Firebase-Functions/functions/service/withdrawalManager.js
  burstcamp/burstcamp/Service/Firebase/FireFunctionsManager.swift
Labels: type: feature, 늘이

#210 [코디네이터] 마이페이지 - 로그인화면으로 이동
  burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
Labels: type: feature, 늘이

#208 [회원가입] indicator 하단뷰, 탈퇴시 재인증처리
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/SceneDelegate.swift
  burstcamp/burstcamp/Coordinator/App/AppCoordinator.swift
  burstcamp/burstcamp/Coordinator/Auth/AuthCoordinator.swift
  burstcamp/burstcamp/Coordinator/Base/CoordinatorEvent.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SighUpDomainView.swift
  burstcamp/burstcamp/Service/KeyChainManager.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Util/Constant/Constant.swift
  burstcamp/burstcamp/Util/Error/FirebaseAuthError.swift
  burstcamp/burstcamp/Util/Error/FirestoreError.swift
  modules/BCResource/BCResource/Generated/Assets+Generated.swift
Labels: type: feature, 기훈

#215 [푸시알림] 탭했을시 Coordinator 이동
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/App/Info.plist
  burstcamp/burstcamp/Coordinator/App/AppCoordinator.swift
  burstcamp/burstcamp/Coordinator/Home/HomeCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Service/Firebase/FirestoreCollection.swift
  burstcamp/burstcamp/Service/FirestoreFCMToken.swift
  burstcamp/burstcamp/Service/UserDefaultsManager.swift
  modules/BCResource/BCResource/Generated/Assets+Generated.swift
Labels: type: feature, 늘이

#217 [탈퇴] LoginManager와 마이페이지 연동
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift
  burstcamp/burstcamp/Service/Firebase/FireFunctionsManager.swift
  burstcamp/burstcamp/Service/LogInManager.swift
  burstcamp/burstcamp/Service/UserManager.swift
Labels: type: feature, 늘이

#219 [리팩토링] 파이어베이스 함수 리팩토링
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Coordinator/Base/ContainFeedDetailCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
  burstcamp/burstcamp/Scene/Common/ViewModel/FeedScrapViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  burstcamp/burstcamp/Service/Firebase/FireFunction/FireFunctionsManager.swift
  burstcamp/burstcamp/Service/Firebase/FireStorage/FireStorageService.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/BCFirestoreService.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/BeforeFirestoreFeedService.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/FirestoreCollection.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/FirestoreService.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/FirestoreUser.swift
  burstcamp/burstcamp/Util/Extension/Combine/Future+async.swift
Labels: type: enhancement, 유탁

#223 [회원탈퇴] reAuth 문제 수정
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/SceneDelegate.swift
  burstcamp/burstcamp/Coordinator/Auth/AuthCoordinator.swift
  burstcamp/burstcamp/Coordinator/Base/CoordinatorEvent.swift
  burstcamp/burstcamp/Coordinator/Base/GithubLogInCoordinator.swift
  burstcamp/burstcamp/Coordinator/MyPage/MyPageCoordinator.swift
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Domain/SignUpDomainViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift
  burstcamp/burstcamp/Service/KeyChainManager.swift
  burstcamp/burstcamp/Service/LogInManager.swift
Labels: type: bug, 기훈

#228 [탈퇴] indicator 및 화면 인터렉션 수정
  burstcamp/burstcamp/Scene/Auth/LogIn/LogInView.swift
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/ViewModel/MyPageViewModel.swift
Labels: type: feature, 늘이

#224 [캐시] etag 정보 삭제
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Service/UserDefaultsManager.swift
  burstcamp/burstcamp/Util/Extension/UI/UIImageView+Cache.swift
Labels: type: enhancement, 늘이

#229 [Functions] feed 삭제 오류 및 추천 피드 수정
  Firebase-Functions/functions/index.js
  Firebase-Functions/functions/service/firestoreManager.js
Labels: type: bug, 늘이

#214 [기능] Error Alert
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Scene/Common/ViewModel/FeedScrapViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController+handleError.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  burstcamp/burstcamp/Service/UserDefaultsManager.swift
  burstcamp/burstcamp/Util/Error/ConvertError.swift
  burstcamp/burstcamp/Util/Error/Error+resolveCategory.swift
  burstcamp/burstcamp/Util/Error/ErrorCategory.swift
  burstcamp/burstcamp/Util/Error/FireStorageError.swift
  burstcamp/burstcamp/Util/Error/FirestoreError.swift
  burstcamp/burstcamp/Util/Error/GithubError.swift
  burstcamp/burstcamp/Util/Error/ImageCacheError.swift
  burstcamp/burstcamp/Util/Error/NetworkError.swift
  burstcamp/burstcamp/Util/Extension/UI/UIResponder+.swift
  burstcamp/burstcamp/Util/Extension/UI/UIViewController+.swift
Labels: type: feature, 유탁

#232 [회원가입] 블로그 타이틀 불러올때 오류 수정
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Service/Firebase/FireFunction/FireFunctionsManager.swift
Labels: type: bug, 늘이

#234 [UI] 다듬기
  burstcamp/burstcamp/Coordinator/TabBar/TabBarPage.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultUserInfoView.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedHeader.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/RecommendFeedSection/RecommendFeedUserView.swift
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageProfileView.swift
  burstcamp/burstcamp/Service/Firebase/FireStorage/FireStorageService.swift
  burstcamp/burstcamp/Util/Error/FirestoreError.swift
  burstcamp/burstcamp/Util/Extension/UI/UICollectionView+emptyView.swift
  modules/BCResource/BCResource/FontSet.swift
Labels: type: enhancement, 늘이

#235 [앱 실행] Launch Screen 적용 및 애니메이션 적용
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/Base.lproj/LaunchScreen.storyboard
  burstcamp/burstcamp/App/SceneDelegate.swift
  burstcamp/burstcamp/Coordinator/App/AppCoordinator.swift
  burstcamp/burstcamp/Coordinator/Base/Coordinator.swift
  burstcamp/burstcamp/Resource/Assets.xcassets/LaunchScreen.imageset/Contents.json
  burstcamp/burstcamp/Resource/Assets.xcassets/LaunchScreen.imageset/LaunchScreen_Dark 1.png
  burstcamp/burstcamp/Resource/Assets.xcassets/LaunchScreen.imageset/LaunchScreen_Dark.png
  burstcamp/burstcamp/Resource/Assets.xcassets/LaunchScreen.imageset/LaunchScreen_Dark@2x 1.png
  burstcamp/burstcamp/Resource/Assets.xcassets/LaunchScreen.imageset/LaunchScreen_Dark@2x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/LaunchScreen.imageset/LaunchScreen_Dark@3x 1.png
  burstcamp/burstcamp/Resource/Assets.xcassets/LaunchScreen.imageset/LaunchScreen_Dark@3x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/LaunchScreenBackground.colorset/Contents.json
  burstcamp/burstcamp/Scene/Common/View/LoadingView.swift
  burstcamp/burstcamp/Scene/Tab/Home/View/HomeView.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  modules/BCResource/BCResource/Resource/Image.xcassets/AppIcon.appiconset/AppIcon.png
  modules/BCResource/BCResource/Resource/Image.xcassets/AppIcon.appiconset/Contents.json
Labels: type: feature, 유탁

#237 [앱 설정] 세로모드 고정
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/Info.plist
Labels: type: feature, 유탁

#240 [알림] 디테일뷰로 가지 않는 버그 수정
  Firebase-Functions/functions/service/apnsManager.js
  Firebase-Functions/functions/service/firestoreManager.js
  burstcamp/burstcamp/Coordinator/Home/HomeCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
Labels: type: bug, 늘이

#238 [로그인] 로그인 제어 불능상태 해결
  burstcamp/burstcamp/Scene/Auth/LogIn/LoginViewController.swift
  burstcamp/burstcamp/Service/Firebase/FireFunction/FireFunctionsManager.swift
Labels: type: bug, priority: 긴급, 기훈

#242 [버그수정] 블로그 주소 마지막 "/" 처리 및 Feed 업데이트 함수 생성
  Firebase-Functions/functions/index.js
  Firebase-Functions/functions/service/firestoreManager.js
  burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultBadgeView.swift
  burstcamp/burstcamp/Util/Constant/URLRegularExpression.swift
Labels: type: bug, 늘이

#230 [Refactor] fetcher, updater을 이용한 Feed Scrap 기능 연동
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Coordinator/Base/ContainFeedDetailCoordinator.swift
  burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
  burstcamp/burstcamp/FeedLocalDataSource.swift
  burstcamp/burstcamp/FeedRemoteDataSource.swift
  burstcamp/burstcamp/Model/Feed/Feed.swift
  burstcamp/burstcamp/Model/Feed/FeedAPIModel.swift
  burstcamp/burstcamp/Model/Feed/FeedCellType.swift
  burstcamp/burstcamp/Model/Feed/FeedWriter.swift
  burstcamp/burstcamp/Model/User.swift
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Contents.json
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github.png
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github@2x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github@3x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github_dark.png
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github_dark@2x.png
  burstcamp/burstcamp/Resource/Assets.xcassets/Github.imageset/Github_dark@3x.png
  burstcamp/burstcamp/Scene/Common/View/DefaultToggleButton.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/Footer/NormalFeedCellFooter.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Scene/Common/ViewModel/FeedScrapViewModel.swift
  burstcamp/burstcamp/Scene/Common/ViewModel/ScrapViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewController/FeedDetailViewController.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/BCFirestoreService.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/BeforeFirestoreFeedService.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/FirestoreCollection.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/FirestoreService.swift
  burstcamp/burstcamp/Util/Extension/AsyncCompatible/Future+Async.swift
  burstcamp/burstcamp/Util/Extension/AsyncCompatible/Publisher+Async.swift
  burstcamp/burstcamp/Util/Extension/AsyncCompatible/Sequence+Async.swift
  burstcamp/burstcamp/Util/Extension/Combine/Publisher+Extension.swift
  burstcamp/burstcamp/Util/Extension/Combine/UIControl+Combine.swift
  modules/BCFetcher/BCFetcher.xcodeproj/project.pbxproj
  modules/BCFetcher/BCFetcher.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  modules/BCFetcher/BCFetcher/BCFetcher.h
  modules/BCFetcher/BCFetcher/Fetchable.swift
  modules/BCFetcher/BCFetcher/Fetcher.swift
  modules/BCFetcher/BCFetcher/FetchingState.swift
  modules/BCFetcher/BCFetcher/Updater.swift
  modules/BCFetcher/Extension/AnyCancellable+store.swift
Labels: type: enhancement, 승민
