Repository boostcampwm-2022/iOS09-burstcamp, pull requests merged in 2023-02, with the labels that each got.

#319 [Feature] UIViewController extension에 indicator view 설정
  burstcamp/burstcamp/Presentation/Auth/LogIn/View/LogInView.swift
  burstcamp/burstcamp/Presentation/Auth/LogIn/ViewController/LogInViewController.swift
  burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogView.swift
  burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Presentation/Coordinator/App/AppCoordinator.swift
  burstcamp/burstcamp/Presentation/Coordinator/Auth/AuthCoordinator.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/View/MyPageView.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/BCFirestoreUserListener.swift
  burstcamp/burstcamp/Util/Extension/UI/ViewController/UIViewController+.swift
Labels: type: feature, 유탁

#320 [Fix] iOS 15.0 에서 애플 로그인 - apple image 안 보이던 오류 수정
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Presentation/Auth/LogIn/View/LogInView.swift
  burstcamp/burstcamp/Presentation/Common/View/Button/AuthButton.swift
  burstcamp/burstcamp/Service/Firebase/Auth/BCFirebaseAuthService.swift
Labels: type: bug, 유탁

#324 [Refactor] MVVM Input <-> Output
  burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Presentation/Coordinator/MyPage/MyPageCoordinator.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewController/FeedDetailViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/Home/View/HomeView.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewModel/MyPageViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  burstcamp/burstcamp/Service/Singleton/UserManager.swift
  burstcamp/burstcamp/Util/Error/ViewModel/HomeViewModelError.swift
  burstcamp/burstcamp/Util/Extension/UI/ViewController/UIViewController+.swift
Labels: type: enhancement, 유탁

#325 [Remove] BCFetcher & Realm Manager 제거
  burstcamp/Modules/Manager/.gitkeep
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Data/Local/FeedLocalDataSource.swift
  burstcamp/burstcamp/Data/Local/FeedRealmDataSource.swift
  burstcamp/burstcamp/Data/Local/FeedSingletonDataSource.swift
  burstcamp/burstcamp/Data/Network/FeedRemote/FeedRemoteDataSource.swift
  burstcamp/burstcamp/Domain/Model/Feed/RealmModel/Feed+RealmCompatible.swift
  burstcamp/burstcamp/Domain/Model/Feed/RealmModel/FeedRealmModel.swift
  burstcamp/burstcamp/Domain/Model/Feed/RealmModel/FeedWriter+RealmCompatible.swift
  burstcamp/burstcamp/Domain/Model/Feed/RealmModel/FeedWriterRealmModel.swift
  burstcamp/burstcamp/Domain/Model/User/Domain.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  modules/BCFetcher/BCFetcher.xcodeproj/project.pbxproj
  modules/BCFetcher/BCFetcher.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  modules/BCFetcher/BCFetcher.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  modules/Manager/RealmManager/RealmManager.xcodeproj/project.pbxproj
  modules/Manager/RealmManager/RealmManager.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  modules/Manager/RealmManager/RealmManager.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  modules/Manager/RealmManager/RealmManager.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 유탁

#329 [fix] profileImage가 삭제시 에러 처리
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
Labels: type: bug, 유탁

#330 [Feature] 클라우드 함수에서 추천 피드 설정
  Firebase-Functions/functions/service/firestoreManager.js
Labels: type: feature, 유탁

#331 [Feat] 닉네임 정책
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/UserRepository/UserRepository.swift
  burstcamp/burstcamp/Domain/Model/User/User.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageEdit/DefaultMyPageEditUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageEdit/MyPageEditUseCase.swift
  burstcamp/burstcamp/Presentation/Common/View/Label/DefaultPaddingLabel.swift
  burstcamp/burstcamp/Presentation/Coordinator/MyPage/MyPageCoordinator.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/Edit/Enum/MyPageEditValidation.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/Edit/View/MyPageEditView.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/Edit/ViewController/MyPageEditViewController.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/Edit/ViewModel/MyPageEditViewModel.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/BCFirestoreService.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/FirestoreService.swift
  burstcamp/burstcamp/Util/Constant/URLRegularExpression.swift
  burstcamp/burstcamp/Util/Extension/Combine/UIControl+Combine.swift
  burstcamp/burstcamp/Util/Extension/Type/String+.swift
  burstcamp/burstcamp/Util/Validator/MyPageEditValidationResult.swift
  burstcamp/burstcamp/Util/Validator/Validator.swift
Labels: type: feature, 유탁

#332 [Feature] FeedDetail View - loading gif 뷰 설정
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp/Presentation/Tab/Detail/View/EmptyView/LoadingFeedView.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/View/FeedDetailView.swift
  burstcamp/burstcamp/Resource/gif/LoadingBurstcamper.gif
Labels: type: feature, 유탁

#328 [Refactor] notification usecase 생성
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Data/Repositories/NotificationRepository/DefaultNotificationRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/NotificationRepository/NotificationRepository.swift
  burstcamp/burstcamp/Domain/UseCase/Notification/DefaultNotificationUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Notification/NotificationUseCase.swift
  burstcamp/burstcamp/Service/Singleton/UserDefaultsManager.swift
  burstcamp/burstcamp/Service/UserDefaultsService/DefaultUserDefaultsService.swift
  burstcamp/burstcamp/Service/UserDefaultsService/UserDefaultsService.swift
  burstcamp/burstcamp/Util/Constant/UserDefaultsKey.swift
  burstcamp/burstcamp/Util/Error/Repository/NotificationRepository/NotificationRepositoryError.swift
Labels: type: enhancement, 늘이

#334 [Feature] Firebase 캡슐화
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Service/Firebase/App/BCFirebaseApp.swift
  burstcamp/burstcamp/Service/Firebase/Messaging/BCFirebaseMessaging.swift
  burstcamp/burstcamp/Util/Extension/UI/ViewController/UIResponder+.swift
Labels: type: feature, 유탁

#335 [Feature] firebase 코드 프레임워크화
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Data/Network/GithubLogin/GithubLoginDatasource.swift
  burstcamp/burstcamp/Data/Repositories/BlogRepository/DefaultBlogRepository.swift
  burstcamp/burstcamp/Data/Repositories/FeedRepository/DefaultFeedRepository.swift
  burstcamp/burstcamp/Data/Repositories/ImageRepository/DefaultImageRepository.swift
  burstcamp/burstcamp/Data/Repositories/LoginRepository/DefaultLoginRepository.swift
  burstcamp/burstcamp/Data/Repositories/NotificationRepository/DefaultNotificationRepository.swift
  burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
  burstcamp/burstcamp/Domain/Model/Feed/Feed.swift
  burstcamp/burstcamp/Domain/Model/Feed/FeedWriter.swift
  burstcamp/burstcamp/Domain/Model/User/User.swift
  burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
  burstcamp/burstcamp/Service/Singleton/UserManager.swift
  modules/BCFirebase/BCFirebase.xcodeproj/project.pbxproj
  modules/BCFirebase/BCFirebase.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  modules/BCFirebase/BCFirebase.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  modules/BCFirebase/BCFirebase.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  modules/BCFirebase/BCFirebase/App/BCFirebaseApp.swift
  modules/BCFirebase/BCFirebase/Auth/BCFirebaseAuthService.swift
  modules/BCFirebase/BCFirebase/Auth/FirebaseAuthError.swift
  modules/BCFirebase/BCFirebase/BCFirebase.docc/BCFirebase.md
  modules/BCFirebase/BCFirebase/BCFirebase.h
  modules/BCFirebase/BCFirebase/FireFunction/BCFirebaseFunctionService.swift
  modules/BCFirebase/BCFirebase/FireFunction/FirebaseFunctionError.swift
  modules/BCFirebase/BCFirebase/FireStorage/BCFireStorageService.swift
  modules/BCFirebase/BCFirebase/FireStorage/FireStorageError.swift
  modules/BCFirebase/BCFirebase/Firestore/BCFirestoreService.swift
  modules/BCFirebase/BCFirebase/Firestore/BCFirestoreUserListener.swift
  modules/BCFirebase/BCFirebase/Firestore/FirestoreCollection.swift
  modules/BCFirebase/BCFirebase/Firestore/FirestoreService.swift
  modules/BCFirebase/BCFirebase/Firestore/FirestoreServiceError.swift
  modules/BCFirebase/BCFirebase/Messaging/BCFirebaseMessaging.swift
  modules/BCFirebase/BCFirebase/Model/FCMToken.swift
  modules/BCFirebase/BCFirebase/Model/FeedAPIModel.swift
  modules/BCFirebase/BCFirebase/Model/ScrapFeedAPIModel.swift
  modules/BCFirebase/BCFirebase/Model/UserAPIModel.swift
  modules/BCFirebase/BCFirebase/Util/Encodable+.swift
  modules/BCResource/BCResource/Generated/Assets+Generated.swift
Labels: type: feature, 유탁

#337 [Fix] 노말 피드 이미지 에러
  burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
  burstcamp/burstcamp/Presentation/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
  burstcamp/burstcamp/Presentation/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedCell.swift
  burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedUserView.swift
Labels: type: bug, 유탁

#338 [Feature] 피드 디테일 알람 시 deep link
  Firebase-Functions/functions/index.js
  Firebase-Functions/functions/service/apnsManager.js
  burstcamp/burstcamp/Data/Repositories/FeedRepository/DefaultFeedRepository.swift
  burstcamp/burstcamp/Data/Repositories/FeedRepository/MockUpFeedRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/FeedRepository/FeedRepository.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Detail/DefaultFeedDetailUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Detail/FeedDetailUseCase.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewController/FeedDetailViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/FeedDetailViewModel.swift
Labels: type: feature, 유탁

#339 [Fix] 유저 회원가입시 DB 업데이트
  Firebase-Functions/functions/index.js
  Firebase-Functions/functions/service/firestoreManager.js
  burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/UserRepository/UserRepository.swift
  burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewController.swift
  burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Presentation/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/Edit/View/MyPageEditView.swift
  burstcamp/burstcamp/Util/Extension/Combine/UIControl+Combine.swift
  modules/BCFirebase/BCFirebase/FireFunction/BCFirebaseFunctionService.swift
  modules/BCFirebase/BCFirebase/FireStorage/FireStorageError.swift
Labels: type: feature, 유탁

#340 fix: Indicator 위치 수정
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
Labels: type: bug, 유탁

#341 [fix] 탈퇴시 scrapCount 조정 & removeUserListener
  Firebase-Functions/functions/service/firestoreManager.js
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
Labels: type: bug, 유탁

#343 [Fix] 다중 스크랩 에러 해결
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
Labels: type: bug, 유탁

#345 Fix/scrap page refresh
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
Labels: type: bug, 유탁

#347 [Feat] 탭 바 클릭시 스크롤 최상단 이동
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Util/Protocol/ContainScrollViewController.swift
Labels: type: feature, 유탁

#349 [fix] 게스트 모드시 정보 수정 버튼 제거
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/View/MyPageView.swift
Labels: type: bug, 유탁

#351 [Feature] 신고하기 & 차단하기 추가
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Data/Repositories/FeedRepository/DefaultFeedRepository.swift
  burstcamp/burstcamp/Data/Repositories/FeedRepository/MockUpFeedRepository.swift
  burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/FeedRepository/FeedRepository.swift
  burstcamp/burstcamp/Domain/Model/User/User.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Detail/DefaultFeedDetailUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Detail/FeedDetailUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
  burstcamp/burstcamp/Presentation/Coordinator/Base/ContainFeedDetailCoordinator.swift
  burstcamp/burstcamp/Presentation/Coordinator/Base/CoordinatorEvent.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewController/FeedDetailViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/ActionSheetEvent.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  burstcamp/burstcamp/Util/Protocol/ContainFeedDetailViewController.swift
  modules/BCFirebase/BCFirebase/Firestore/BCFirestoreService.swift
  modules/BCFirebase/BCFirebase/Firestore/FirestoreCollection.swift
  modules/BCFirebase/BCFirebase/Model/UserAPIModel.swift
Labels: type: feature, 유탁

#353 [feat] velog 기본 썸네일 제거
  Firebase-Functions/functions/service/feedAPI.js
Labels: type: feature, 유탁

#354 [Feat] skeleton View 지연 실행
  burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedHeader.swift
  burstcamp/burstcamp/Presentation/Tab/Home/View/HomeView.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
Labels: type: enhancement, 유탁

#356 [fix] 푸시알림 시간 계산 오류
  Firebase-Functions/functions/service/apnsManager.js
Labels: type: bug, 늘이

#357 [fix] 알림 발송 수정
  Firebase-Functions/functions/service/apnsManager.js
Labels: type: bug, 늘이

#358 feat: BCFirebase -> static으로 변경
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/AppDelegate.swift
  modules/BCFirebase/BCFirebase.xcodeproj/project.pbxproj
Labels: type: enhancement, 유탁
