Repository boostcampwm-2022/iOS09-burstcamp, pull requests merged in 2023-01, with the labels that each got.

#249 [푸시알림] 백그라운드 이동 버그 수정
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Coordinator/TabBar/TabBarCoordinator.swift
  burstcamp/burstcamp/Service/UserDefaultsManager.swift
Labels: type: bug, 늘이

#257 Rss Feed 업데이트시 Feed 모델 수정
  Firebase-Functions/functions/service/firestoreManager.js
Labels: type: enhancement, priority: 빨리

#246 [캐시] 네트워크 요청 전 로컬 캐시 이미지 반환
  burstcamp/burstcamp/Scene/Tab/MyPage/View/MyPageEditView.swift
  burstcamp/burstcamp/Service/ImageCacheManager.swift
  burstcamp/burstcamp/Util/Extension/UI/UIImageView+Cache.swift
Labels: type: enhancement, 늘이

#248 [Fetcher] local data를 Realm으로 변경
  burstcamp/.swiftlint.yml
  burstcamp/Modules/Manager/.gitkeep
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp.xcodeproj/xcshareddata/xcschemes/burstcamp.xcscheme
  burstcamp/burstcamp/App/AppDelegate.swift
  burstcamp/burstcamp/Coordinator/Base/ContainFeedDetailCoordinator.swift
  burstcamp/burstcamp/FeedLocalDataSource.swift
  burstcamp/burstcamp/FeedRealmDataSource.swift
  burstcamp/burstcamp/FeedRemoteDataSource.swift
  burstcamp/burstcamp/FeedSingletonDataSource.swift
  burstcamp/burstcamp/Model/Domain.swift
  burstcamp/burstcamp/Model/Feed/Feed.swift
  burstcamp/burstcamp/Model/Feed/FeedAPIModel.swift
  burstcamp/burstcamp/Model/Feed/FeedCellType.swift
  burstcamp/burstcamp/Model/Feed/FeedWriter.swift
  burstcamp/burstcamp/Model/Feed/RealmModel/Feed+RealmCompatible.swift
  burstcamp/burstcamp/Model/Feed/RealmModel/FeedRealmModel.swift
  burstcamp/burstcamp/Model/Feed/RealmModel/FeedWriter+RealmCompatible.swift
  burstcamp/burstcamp/Model/Feed/RealmModel/FeedWriterRealmModel.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultBadgeView.swift
  burstcamp/burstcamp/Scene/Common/View/DefaultUserInfoView.swift
  burstcamp/burstcamp/Scene/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Scene/Common/ViewModel/ScrapViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Detail/View/MockHTMLString.swift
  burstcamp/burstcamp/Scene/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Scene/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Scene/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/FirestoreService.swift
  burstcamp/burstcamp/Service/ImageCacheManager.swift
  burstcamp/burstcamp/Util/Extension/Combine/Publisher+Extension.swift
  modules/BCFetcher/BCFetcher.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  modules/BCFetcher/BCFetcher/Fetchable.swift
  modules/BCFetcher/BCFetcher/Fetcher.swift
  modules/BCFetcher/BCFetcher/Updater.swift
  modules/Manager/RealmManager/RealmManager.xcodeproj/project.pbxproj
  modules/Manager/RealmManager/RealmManager.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  modules/Manager/RealmManager/RealmManager.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  modules/Manager/RealmManager/RealmManager.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  modules/Manager/RealmManager/RealmManager/FetchedResults.swift
  modules/Manager/RealmManager/RealmManager/Model/AutoIncrementable.swift
  modules/Manager/RealmManager/RealmManager/Model/QuerySupportable.swift
  modules/Manager/RealmManager/RealmManager/Model/RealmCompatible.swift
  modules/Manager/RealmManager/RealmManager/Model/SortSupportable.swift
  modules/Manager/RealmManager/RealmManager/Publisher.swift
  modules/Manager/RealmManager/RealmManager/README.md
  modules/Manager/RealmManager/RealmManager/RealmContainer.swift
  modules/Manager/RealmManager/RealmManager/RealmManager.h
  modules/Manager/RealmManager/RealmManager/SortingPolicy.swift
  modules/Manager/RealmManager/RealmManager/WriteTransaction.swift
Labels: type: enhancement, 승민

#261 [Refactor] 254 refactor db모델 수정 반영 swift에서 사용하는 함수 수정
  Firebase-Functions/functions/service/firestoreManager.js
  burstcamp/burstcamp/Data/Network/FeedRemoteDataSource.swift
  burstcamp/burstcamp/Domain/Model/Feed/Feed.swift
  burstcamp/burstcamp/Domain/Model/Feed/FeedAPIModel.swift
Labels: type: enhancement

#270 [Feature] 팩토리 패턴
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/SceneDelegate.swift
  burstcamp/burstcamp/Domain/UseCase/Auth/Login/DefaultLoginUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Auth/Login/LoginUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Auth/SignUp/DefaultSignUpUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Auth/SignUp/SignUpUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Detail/DefaultFeedDetailUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Detail/FeedDetailUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Home/HomeUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageEdit/DefaultMyPageEditUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageEdit/MyPageEditUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/ScrapPage/DefaultScrapPageUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/ScrapPage/ScrapPageUseCase.swift
  burstcamp/burstcamp/Presentation/Auth/LogIn/ViewModel/LogInViewModel.swift
  burstcamp/burstcamp/Presentation/Auth/SignUp/Blog/SignUpBlogViewModel.swift
  burstcamp/burstcamp/Presentation/Auth/SignUp/CamperID/SignUpCamperIDViewModel.swift
  burstcamp/burstcamp/Presentation/Auth/SignUp/Domain/SignUpDomainViewModel.swift
  burstcamp/burstcamp/Presentation/Coordinator/App/AppCoordinator.swift
  burstcamp/burstcamp/Presentation/Coordinator/Auth/AuthCoordinator.swift
  burstcamp/burstcamp/Presentation/Coordinator/Base/ContainFeedDetailCoordinator.swift
  burstcamp/burstcamp/Presentation/Coordinator/Base/Coordinator.swift
  burstcamp/burstcamp/Presentation/Coordinator/Home/HomeCoordinator.swift
  burstcamp/burstcamp/Presentation/Coordinator/MyPage/MyPageCoordinator.swift
  burstcamp/burstcamp/Presentation/Coordinator/ScrapPage/ScrapPageCoordinator.swift
  burstcamp/burstcamp/Presentation/Coordinator/TabBar/TabBarCoordinator.swift
  burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
  burstcamp/burstcamp/Presentation/Factory/DependencyFactoryProtocol.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/Edit/ViewModel/MyPageEditViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewModel/MyPageViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
Labels: type: feature, 유탁

#271 [refactor] 앱 버전 target 14.0 -> 15.0
  burstcamp/burstcamp.xcodeproj/project.pbxproj
Labels: type: feature, 유탁

#278 [Refactor] 마이 페이지 usecase 생성
  burstcamp/burstcamp/App/SceneDelegate.swift
  burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/UserRepository/UserRepository.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageUseCase.swift
  burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewModel/MyPageViewModel.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/BCFirestoreService.swift
  burstcamp/burstcamp/Service/Singleton/DarkmodeManager.swift
  burstcamp/burstcamp/Service/Singleton/KeyChainManager.swift
Labels: type: enhancement, 유탁

#280 [Refactor]collectionview -> diffable datasource로 변경
  burstcamp/burstcamp/Domain/Model/Feed/Feed.swift
  burstcamp/burstcamp/Domain/Model/Feed/FeedWriter.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
Labels: type: enhancement, 유탁

#285 Feature/284 feat feeddetail에서 스크랩 시 home에도 적용
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Domain/UseCase/Tab/Detail/DefaultFeedDetailUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Detail/FeedDetailUseCase.swift
  burstcamp/burstcamp/Presentation/Coordinator/Base/ContainFeedDetailCoordinator.swift
  burstcamp/burstcamp/Presentation/Coordinator/Home/HomeCoordinator.swift
  burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewController/FeedDetailViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Util/Error/ViewModel/FeedDetailViewModelError.swift
  burstcamp/burstcamp/Util/Protocol/ContainFeedDetailViewController.swift
Labels: type: feature, 유탁

#287 [Feature]scrappage usecase 구현
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Data/Repositories/FeedRepository/DefaultFeedRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/FeedRepository/FeedRepository.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/ScrapPage/DefaultScrapPageUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/ScrapPage/ScrapPageUseCase.swift
  burstcamp/burstcamp/Presentation/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Presentation/Coordinator/ScrapPage/ScrapPageCoordinator.swift
  burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewModel/FeedDetailViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/Home/View/RecommendFeedSection/RecommendFeedCell.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/View/ScrapPageView.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewController/ScrapPageViewController.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/BCFirestoreService.swift
  burstcamp/burstcamp/Service/Firebase/Firestore/FirestoreServiceError.swift
  burstcamp/burstcamp/Service/Singleton/UserManager.swift
  burstcamp/burstcamp/Util/Error/ViewModel/ScrapViewModelError.swift
Labels: type: feature, 유탁

#288 [Refactor] Diffable DataSource 를 위한 DiffableFeed
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Data/Local/FeedSingletonDataSource.swift
  burstcamp/burstcamp/Data/Network/FeedRemote/FeedRemoteDataSource.swift
  burstcamp/burstcamp/Domain/Model/Feed/DiffableFeed.swift
  burstcamp/burstcamp/Domain/Model/Feed/Feed.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
Labels: type: enhancement, 유탁

#290 feat: Coordinator에게 URL 전달해서 Safari 연동
  burstcamp/burstcamp/Presentation/Coordinator/Base/CoordinatorEvent.swift
  burstcamp/burstcamp/Presentation/Coordinator/Home/HomeCoordinator.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
Labels: type: feature, 유탁

#292 [Feature] skeleton View
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  burstcamp/burstcamp/Presentation/Common/Updater.swift
  burstcamp/burstcamp/Presentation/Common/View/Badge/DefaultBadgeLabel.swift
  burstcamp/burstcamp/Presentation/Common/View/Badge/DefaultBadgeView.swift
  burstcamp/burstcamp/Presentation/Common/View/Button/DefaultButton.swift
  burstcamp/burstcamp/Presentation/Common/View/Button/DefaultToggleButton.swift
  burstcamp/burstcamp/Presentation/Common/View/ImageView/DefaultProfileImageView.swift
  burstcamp/burstcamp/Presentation/Common/View/Label/DefaultImageLabel.swift
  burstcamp/burstcamp/Presentation/Common/View/Label/DefaultMultilLineLabel.swift
  burstcamp/burstcamp/Presentation/Common/View/LoadingVIew/LoadingView.swift
  burstcamp/burstcamp/Presentation/Common/View/NormalFeedCell/Footer/NormalFeedCellFooter.swift
  burstcamp/burstcamp/Presentation/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
  burstcamp/burstcamp/Presentation/Common/View/NormalFeedCell/NormalFeedCell.swift
  burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedCell.swift
  burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedHeader.swift
  burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedUserView.swift
  burstcamp/burstcamp/Presentation/Common/View/TextField/DefaultTextField.swift
  burstcamp/burstcamp/Presentation/Common/View/UserInfoView/DefaultUserInfoView.swift
  burstcamp/burstcamp/Presentation/Common/ViewModel/.gitkeep
  burstcamp/burstcamp/Presentation/Common/ViewModel/ScrapViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/ViewController/FeedDetailViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/DataSource/HomeFeedListSkeletonDiffableDatasource.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Util/Constant/Constant.swift
  burstcamp/burstcamp/Util/Extension/Type/TypeConversion.swift
Labels: type: feature, 유탁

#294 [Feat] UILabel에 baseLineOffset 적용
  burstcamp/burstcamp/Util/Extension/UI/View/UILabel+LineHeight.swift
Labels: type: feature, 유탁

#296 [Fix] 295 에러 다른 기기에서 로그인시 재 가입해야하던 오류
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/UserRepository/UserRepository.swift
  burstcamp/burstcamp/Domain/UseCase/Auth/Login/DefaultLoginUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Auth/Login/LoginUseCase.swift
  burstcamp/burstcamp/Presentation/Auth/LogIn/ViewModel/LogInViewModel.swift
  burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
  burstcamp/burstcamp/Service/Singleton/UserManager.swift
  burstcamp/burstcamp/Util/Error/Repository/UserRepositoryError.swift
  burstcamp/burstcamp/Util/Error/UseCase/LoginUseCaseError.swift
Labels: type: bug, 유탁

#298 [Refactor] HomeViewController에서 FirestoreService 제거
  burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Home/HomeUseCase.swift
  burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Service/Singleton/UserManager.swift
  burstcamp/burstcamp/Util/Error/ViewModel/HomeViewModelError.swift
Labels: type: enhancement, 유탁

#301 [Feat] Cloud Functions 유저 탈퇴 기능 추가 및 에러 수정
  Firebase-Functions/functions/index.js
  Firebase-Functions/functions/service/firestoreManager.js
  Firebase-Functions/functions/service/test/mockUpService.js
  Firebase-Functions/functions/service/withdrawalManager.js
Labels: type: bug, type: feature, 유탁

#303 Feat/302 feat 썸네일 사진 유무에 따른 normalfeedcell 업데이트
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Data/Repositories/FeedRepository/MockUpFeedRepository.swift
  burstcamp/burstcamp/Presentation/Common/View/NormalFeedCell/Main/NormalFeedCellMain.swift
  burstcamp/burstcamp/Service/Test/TestCounter.swift
  burstcamp/burstcamp/Util/Error/Repository/FeedRepository/MockUpFeedRepositoryError.swift
  burstcamp/burstcamp/Util/Error/Repository/UserRepository/UserRepositoryError.swift
Labels: type: feature, 유탁

#305 Fix/266 에러 처리 블로그 html 파싱 시 408 에러 처리
  Firebase-Functions/functions/index.js
  Firebase-Functions/functions/service/feedAPI.js
  Firebase-Functions/functions/service/firestoreManager.js
  Firebase-Functions/functions/service/test/mockUpHTMLData.js
  Firebase-Functions/functions/service/test/testRSSParsing.js
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Presentation/Tab/Detail/View/EmptyView/EmptyFeedView.swift
  burstcamp/burstcamp/Presentation/Tab/Detail/View/FeedDetailView.swift
  modules/BCResource/BCResource/Generated/Assets+Generated.swift
  modules/BCResource/BCResource/ImageSet.swift
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamperStun100.imageset/Contents.json
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamperStun100.imageset/burstcamperStun100.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamperStun100.imageset/burstcamperStun100@2x.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamperStun100.imageset/burstcamperStun100@3x.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamperStun100.imageset/burstcamperStunDark100.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamperStun100.imageset/burstcamperStunDark100@2x.png
  modules/BCResource/BCResource/Resource/Image.xcassets/burstcamperStun100.imageset/burstcamperStunDark100@3x.png
Labels: type: bug, 유탁

#306 [Fix] Cloud Functions에서 피드업데이트 에러
  Firebase-Functions/functions/service/feedAPI.js
Labels: type: bug

#308 [Feature] 애플 로그인으로 게스트 모드 로그인
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/App/SceneDelegate.swift
  burstcamp/burstcamp/Data/Repositories/LoginRepository/DefaultLoginRepository.swift
  burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/LoginRepository/LoginRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/UserRepository/UserRepository.swift
  burstcamp/burstcamp/Domain/Model/User/Domain.swift
  burstcamp/burstcamp/Domain/Model/User/Login/LoginProvider.swift
  burstcamp/burstcamp/Domain/Model/User/User.swift
  burstcamp/burstcamp/Domain/UseCase/Auth/Login/DefaultLoginUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Auth/Login/LoginUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageUseCase.swift
  burstcamp/burstcamp/Presentation/Auth/LogIn/View/LogInView.swift
  burstcamp/burstcamp/Presentation/Auth/LogIn/ViewController/LogInViewController.swift
  burstcamp/burstcamp/Presentation/Auth/LogIn/ViewModel/LogInViewModel.swift
  burstcamp/burstcamp/Presentation/Common/Base/AppleAuthViewController.swift
  burstcamp/burstcamp/Presentation/Common/View/Button/AuthButton.swift
  burstcamp/burstcamp/Presentation/Common/View/ImageView/DefaultProfileImageView.swift
  burstcamp/burstcamp/Presentation/Coordinator/App/AppCoordinator.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/View/MyPageProfileView.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/View/MyPageView.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewModel/MyPageViewModel.swift
  burstcamp/burstcamp/Service/Firebase/Auth/BCFirebaseAuthService.swift
  burstcamp/burstcamp/Util/Error/Repository/UserRepository/UserRepositoryError.swift
  burstcamp/burstcamp/Util/Extension/Combine/UIControl+Combine.swift
  burstcamp/burstcamp/Util/Extension/Type/String+sha256.swift
  burstcamp/burstcamp/Util/Extension/UI/ViewController/UIViewController+.swift
  burstcamp/burstcamp/burstcamp.entitlements
Labels: type: feature, 유탁

#310 [Feature] 추천피드 예외처리
  burstcamp/burstcamp.xcodeproj/project.pbxproj
  burstcamp/burstcamp/Data/Local/FeedMockUpDatasource.swift
  burstcamp/burstcamp/Data/Repositories/FeedRepository/DefaultFeedRepository.swift
  burstcamp/burstcamp/Data/Repositories/FeedRepository/MockUpFeedRepository.swift
  burstcamp/burstcamp/Domain/Interfaces/FeedRepository/FeedRepository.swift
  burstcamp/burstcamp/Domain/Model/Feed/FeedWriter.swift
  burstcamp/burstcamp/Domain/UseCase/Auth/SignUp/DefaultSignUpUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
  burstcamp/burstcamp/Presentation/Auth/LogIn/ViewModel/LogInViewModel.swift
  burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedCell.swift
  burstcamp/burstcamp/Presentation/Common/View/RecommendCell/RecommendFeedUserView.swift
  burstcamp/burstcamp/Presentation/Factory/DependencyFactory.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewModel/HomeViewModel.swift
  burstcamp/burstcamp/Presentation/Tab/ScrapPage/ViewModel/ScrapPageViewModel.swift
  burstcamp/burstcamp/Util/Error/Repository/FeedRepository/FeedRepositoryError.swift
Labels: type: feature, 유탁

#314 Feature/유저 업데이트날짜
  burstcamp/burstcamp/Data/Repositories/UserRepository/DefaultUserRepository.swift
  burstcamp/burstcamp/Domain/Model/User/User.swift
  burstcamp/burstcamp/Domain/UseCase/Auth/SignUp/DefaultSignUpUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/DefaultMyPageUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageEdit/DefaultMyPageEditUseCase.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/MyPage/MyPageUseCase.swift
  burstcamp/burstcamp/Presentation/Auth/LogIn/ViewModel/LogInViewModel.swift
  burstcamp/burstcamp/Presentation/Coordinator/App/AppCoordinator.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/Edit/View/MyPageEditView.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewController/MyPageViewController.swift
  burstcamp/burstcamp/Presentation/Tab/MyPage/MyPage/ViewModel/MyPageViewModel.swift
  burstcamp/burstcamp/Service/Firebase/Model/UserAPIModel.swift
  burstcamp/burstcamp/Util/Extension/Type/Date+FormatString.swift
Labels: type: feature, 유탁

#316 [Fix] 추천피드 에러
  burstcamp/burstcamp/Data/Local/FeedMockUpDatasource.swift
  burstcamp/burstcamp/Domain/UseCase/Tab/Home/DefaultHomeUseCase.swift
  burstcamp/burstcamp/Presentation/Tab/Home/View/HomeView.swift
  burstcamp/burstcamp/Presentation/Tab/Home/ViewController/HomeViewController.swift
Labels: type: bug, 유탁
